language: php

php: [5.4, 5.5, 5.6, 7.0, 7.1]

before_script:
  - sudo apt-get install php5-cgi
  - composer selfupdate
  - composer install --prefer-source

script:
  - ./vendor/bin/phpspec run --format=pretty
  - ./vendor/bin/behat -fprogress --strict
